### ISSUE TITLE
Some exceptions raised during training

### ISSUE THREAD

**Issue by terryzhao127** [rwightman/pytorch-pommerman-rl#1]
Every 100 updates, there is an exception raised.

For example, the 100th update is normal.
```
Updates 100, num timesteps 8080, FPS 610, last 10 mean/median reward -1.0/-1.0, min / max reward -1.0/-1.0, value/action loss 1.79038/0.00075
```

**Then an exception is raised:**

```
/home/guikarist/miniconda3/envs/graduate-project/lib/python3.6/site-packages/matplotlib/figure.py:445: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  % get_backend())
Traceback (most recent call last):
  File "/home/guikarist/miniconda3/envs/graduate-project/lib/python3.6/site-packages/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/home/guikarist/miniconda3/envs/graduate-project/lib/python3.6/site-packages/urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "/home/guikarist/miniconda3/envs/graduate-project/lib/python3.6/site-packages/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/guikarist/miniconda3/envs/graduate-project/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/guikarist/miniconda3/envs/graduate-project/lib/python3.6/site-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/guikarist/miniconda3/envs/graduate-project/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/guikarist/miniconda3/envs/graduate-project/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/guikarist/miniconda3/envs/graduate-project/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/guikarist/miniconda3/envs/graduate-project/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/home/guikarist/miniconda3/envs/graduate-project/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/home/guikarist/miniconda3/envs/graduate-project/lib/python3.6/site-packages/urllib3/connection.py", line 181, in connect
    conn = self._new_conn()
  File "/home/guikarist/miniconda3/envs/graduate-project/lib/python3.6/site-packages/urllib3/connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f9af5d747f0>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/guikarist/miniconda3/envs/graduate-project/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/guikarist/miniconda3/envs/graduate-project/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/guikarist/miniconda3/envs/graduate-project/lib/python3.6/site-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /events (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9af5d747f0>: Failed to establish a new connection: [Errno 111] Connection refused',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/guikarist/miniconda3/envs/graduate-project/lib/python3.6/site-packages/visdom/__init__.py", line 548, in _send
    data=json.dumps(msg),
  File "/home/guikarist/miniconda3/envs/graduate-project/lib/python3.6/site-packages/requests/sessions.py", line 581, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/home/guikarist/miniconda3/envs/graduate-project/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/guikarist/miniconda3/envs/graduate-project/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/guikarist/miniconda3/envs/graduate-project/lib/python3.6/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /events (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9af5d747f0>: Failed to establish a new connection: [Errno 111] Connection refused',))
Exception in user code:
------------------------------------------------------------
```

And next update follows:

```
Updates 110, num timesteps 8880, FPS 613, last 10 mean/median reward -1.0/-1.0, min / max reward -1.0/-1.0, value/action loss 1.78657/0.00077
```

But it seems that these exceptions don't affect training. Is it a problem?

**Comment by rwightman** [comment]
It's the visdom client trying to connect to the visdom server. It can be ignored but is annoying. 

Either run main.py with '--no-vis' or, leave it enabled and run the visdom server ('visdom' with the python environment that has visdom installed in it currently active). Then you can monitor progress at http://localhost:8097 

Note that the author of the RL base I'm using changed his code recently to use a python notebook based viz setup...  https://github.com/ikostrikov/pytorch-a2c-ppo-acktr-gail

**Comment by terryzhao127** [comment]
Thanks for your replying!

I found that Baselines had already implemented a2c, etc. Is it needed to use project which your codes are based on rather than directly Baselines?

**Comment by terryzhao127** [comment]
Now I have another error in running a `enjoy.py`:

My command:
```
python enjoy.py --load-path trained_models/a2c/PommeFFACompetitionFast-v0.pt 
```

Output:

```
Traceback (most recent call last):
  File "enjoy.py", line 72, in <module>
    train=False)
  File "/home/guikarist/Projects/graduate-project/pytorch-pommerman-rl/models/factory.py", line 19, in create_policy
    **nn_kwargs)
  File "/home/guikarist/Projects/graduate-project/pytorch-pommerman-rl/models/model_pomm.py", line 143, in __init__
    batch_norm=batch_norm)
  File "/home/guikarist/Projects/graduate-project/pytorch-pommerman-rl/models/model_pomm.py", line 76, in __init__
    self.conv1 = nn.Conv2d(input_shape[0], num_channels, 3, stride=1, padding=1)
  File "/home/guikarist/miniconda3/envs/graduate-project/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 315, in __init__
    False, _pair(0), groups, bias)
  File "/home/guikarist/miniconda3/envs/graduate-project/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 38, in __init__
    out_channels, in_channels // groups, *kernel_size))
RuntimeError: $ Torch: invalid memory size -- maybe an overflow? at /opt/conda/conda-bld/pytorch_1550780889552/work/aten/src/TH/THGeneral.cpp:188
```

**Comment by rwightman** [comment]
You have to specify the same env name that you used for train when you run enjoy or it will default to Pong

**Comment by terryzhao127** [comment]
Thanks so much! All things work right now.

**Comment by terryzhao127** [comment]
BTW, do you have any suggestions on accelerating the training process? Now it takes me 2 days to train `4e7` steps on `two 1080ti with SLI` and `a 20 core i9 CPU`.

**Comment by terryzhao127** [comment]
Sorry to ask so many questions!

One last question: does it support multi-threading!

Thank you!

**Comment by terryzhao127** [comment]
> Sorry to ask so many questions!
> 
> One last question: does it support multi-threading!
> 
> Thank you!

I've found the `--num-processes NUM_PROCESSES` options.
